### PR TITLE
Adding Github Actions CI

### PR DESCRIPTION
**Pull request by gAmUssA**
- add GH action and dependabot
- addded gitignore and go.sum

cc @hishamhm

### CODE REVIEW

**Comment by hishamhm** [comment]
@gAmUssA could you trigger manually the Action in the `gh_action_ci` branch from your repo, so we can give this a test run before merging? thanks!

**Comment by gAmUssA** [comment]
@hishamhm how? 
I use https://github.com/nektos/act to validate GH actions locally (attached log).
[act.txt](https://github.com/Kong/proxy-wasm-go-rate-limiting/files/12317733/act.txt)

**Comment by hishamhm** [comment]
@gAmUssA I've been bitten by inconsistencies between act and the real GitHub Actions environment before, so I'd like to see a green build before activating CI here. 

> @hishamhm how?

Now that's an interesting question. If the option in the Actions tab doesn't show up, then I guess the workflow needs to be merged so it can be triggered. Maybe it's possible by opening a PR against your own repo, then it might show the Action running (maybe it is PRs just don't trigger Actions added from third-party repos). Worst case you'd have to merge the workflow to your fork, then it would certainly run there and we'd get the validation. That's probably the simplest way to go about it.

**Comment by gAmUssA** [comment]
@hishamhm thanks for your reply.

Why not just merge and see in this repo? It's still an example project. All this hustle merging to own fork sound like a busy work. Your call...

**Comment by hishamhm** [comment]
> Why not just merge and see in this repo?

Because if I merge it and it goes red then I have a sudden unplanned fire to put out. #1 rule of taking OSS contributions is evaluating the amount of maintenance work it adds to the project. It is on the contributor to show that the contribution works. ;) Can't "merge it and see", sorry!

**Comment by gAmUssA** [comment]
I thought we are on the same team…
Anyway, I will get back to you with a demonstration of the value of this pr. Stay tuned ;)

**Comment by gAmUssA** [comment]
@hishamhm see https://github.com/gAmUssA/proxy-wasm-go-rate-limiting/actions/runs/5870646696

**Comment by hishamhm** [comment]
@gAmUssA Thank you! I have fixed the merge conflict, rebased the history and merged manually! I see Dependabot is already doing its thing, which means CI is running!

**Comment by hishamhm** [comment]
Looking forward to the integration test PR and most importantly that code fix it also included. Cheers!

**Pull request closed without merging**
